"""update shopping cart

Revision ID: cca0072db6ad
Revises: f32d30b909bf
Create Date: 2023-10-03 20:34:41.867946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca0072db6ad'
down_revision = 'f32d30b909bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_cart_product_association_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cart_product_association_cart_id_shopping_cart'), 'shopping_cart', ['cart_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_cart_product_association_cart_id_shopping_cart'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cart_product_association_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
