"""adds password_hash

Revision ID: ee7a618a369b
Revises: b8dd4979bad4
Create Date: 2023-10-05 15:54:41.858100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7a618a369b'
down_revision = 'b8dd4979bad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_name_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_name_key', ['name'])

    # ### end Alembic commands ###
